### ISSUE TITLE
custom auth server use grpc service fail

### ISSUE THREAD

**Issue by riverlee2014** [k8sgateway/k8sgateway#6116]
### Gloo Edge Version

1.10.x (latest stable)

### Kubernetes Version

docker-compose-consul

### Describe the bug

Hi, I install gloo edge by docker-compose consul mode. when try to testing config custom auth server, I use httpService successfuly! but it's work fail by grpc service.

### Steps to reproduce the bug

1. modify the docker-compose dir data file: ${install-dir}/install/gloo-docker-compose/data/gloo-system/default.yaml
```
gloo:
  xdsBindAddr: 0.0.0.0:9977
consul:
  address: consul:8500
  serviceDiscovery: {}
consulKvSource: {}
consulKvArtifactSource: {}
discoveryNamespace: gloo-system
metadata:
  name: default
  namespace: gloo-system
refreshRate: 15s
extauth:
   extauthzServerRef:
     name: ext-authz
     namespace: gloo-system
   requestBody:
     maxRequestBytes: 10240
   requestTimeout: 0.5s
vaultSecretSource:
  address: http://vault:8200
  token: root
```
2. start up one grpc authz server use api v3, and register to consul service as upstream
3. with the demo petstore config route, test by curl tool: `curl --write-out "$http_code" http://localhost:8080/all-pets`
4. tail -f the log of grpc authz  server, it show errors as:
```
Mar 18, 2022 7:47:07 PM io.grpc.netty.shaded.io.grpc.netty.NettyServerTransport notifyTerminated
INFO: Transport failed
io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2Exception: Unexpected HTTP/1.x request: POST /envoy.service.auth.v3.Authorization/Check
        at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:108)
        at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.readClientPrefaceString(Http2ConnectionHandler.java:302)
        at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:239)
        at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:438)
        at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
        at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
        at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
        at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
        at io.grpc.netty.shaded.io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
        at io.grpc.netty.shaded.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
        at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.grpc.netty.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)

```

### Expected Behavior

The envoy can redirect the http request to the grpc authz server

**Comment by chrisgaun** [comment]
Thanks for this.
